#!/bin/bash
# PHPTeleBotWrt Manager (Installer, Updater, Uninstaller)
#--------------------------------------------------------
# Script by Helmi Amirudin <helmiau.com>
# If you use some codes frome here, please give credit to www.helmiau.com
#--------------------------------------------------------
SCRIPTNAME="$(basename "$0")"
INSDIR="/root/PHPTeleBotWrt" # Install directory
TLNAME="PHPTeleBotWrt"

# Installer command
if [[ $1 == "i" ]]; then
	# Check package and install requirements
	echo -e "Updating package repositories for $TLNAME..." && opkg update
	
	# Try install git, git-http, bc is not installed
	echo -e "Try to install git, git-http, bc, screen..." 
	if [[ $(opkg list-installed | grep -c "^git -\|^git-http -\|bc -\|screen -") < 4 ]]; then
		pkgname="git"
		if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
		pkgname="git-http"
		if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
		pkgname="bc"
		if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
		pkgname="screen"
		if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
	else
		echo -e "Package: git, git-http, bc, screen already installed." 
	fi
	
	# Try install PHP if php8/php7 is not installed
	echo -e "Try to install php8/php7..." 
	if [[ $(ls {/bin,/usr/bin,/usr/sbin} | grep -c "^php8-cli\|^php7-cli") < 1 ]] && [[ $(ls {/usr/lib/php,/usr/lib/php8} | grep -c "^curl.so") < 1 ]];then
		# install php7 if php8 is not available on the repo
		if [[ $(opkg list | grep -c "^php8-cli -") == 0 ]];then
			# Try install php7
			echo -e "Try to install php7 deps..." 
			pkgname="php7-cli"
			if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
			pkgname="php7-mod-curl"
			if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
		else
			# Try install php8
			echo -e "Try to install php8 deps..."
			pkgname="php8-cli"
			if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
			pkgname="php8-mod-curl"
			if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then echo -e "Installing [$pkgname]..." && opkg install $pkgname ; fi
		fi
	else
		echo -e "Package: PHP packages already installed." 
	fi
	
	# Rechecking all required packages
	if [[ $(opkg list-installed | grep -c "^git -\|^git-http -\|bc -\|screen -") == "4" ]] && [[ $(opkg list-installed | grep -c "^php8-cli -\|^php8-mod-curl -") == "2" || $(opkg list-installed | grep -c "^php7-cli -\|^php7-mod-curl -") == "2" ]]; then
		echo "All/some required packages is not installed correctly or something wrong, exiting manager..."
		exit 1
	fi

	# Remove older version if available
	if [[ -d "$INSDIR" ]]; then
		echo -e "Old files of $TLNAME detected! removing..."
		[ -e "$INSDIR"/databot ] && mv "$INSDIR"/databot "$INSDIR"-databot.bak
		rm -rf "$INSDIR"
	fi

	# Cloning repo
	echo -e "Downloading $TLNAME files..."
	git clone https://github.com/helmiau/PHPTeleBotWrt "$INSDIR"
	
	if [ $? -eq 0 ]; then
		echo -e "$TLNAME downloaded successfully."
	else
		echo -e "Error downloading $TLNAME binaries, exiting manager..."
		exit 1
	fi

	# Setting up permissions
	echo -e "Setting up $TLNAME file permissions..."
	chmod 0755 -R "$INSDIR"/*
	
	# Restore databot backup if available
	if [[ -e "$INSDIR"-databot.bak ]]; then
		echo -e "Backup found! Restoring $TLNAME databot backup..."
		mv "$INSDIR"-databot.bak "$INSDIR"/databot
	else
		echo -n "💬 Enter Bot Token: "
		read -r btoken
		echo -n "🤖 Enter Bot Username (without @): "
		read -r buser

		echo -e "\n🔨 Editing $TLNAME telegram data with your Bot Token & Bot Username..."
		echo -e "$btoken" > "$INSDIR"/databot
		echo -e "$buser" >> "$INSDIR"/databot

		echo -e "✔️ $TLNAME telegram data was edited successfully."
	fi

	# Success notif
	echo -e "✔️ $TLNAME installed successfully, you can run this program."

# Update command
elif [[ $1 == "u" ]]; then
	# Update CMD
	echo -e "Updating $TLNAME..."
	
	# Backup databot if available
	[ -e "$INSDIR"/databot ] && echo -e "$TLNAME databot detected! backing up..." && mv "$INSDIR"/databot "$INSDIR"-databot.bak

	cd "$INSDIR"
	git reset --hard
	git pull
	chmod 0755 -R "$INSDIR"/*

	# Restore databot if available
	[ -e "$INSDIR"-databot.bak ] && echo -e "Backup found! Restoring $TLNAME databot backup..." && mv "$INSDIR"-databot.bak "$INSDIR"/databot

# Remover/Uninstaller command
elif [[ $1 == "ra" ]] || [[ $1 == "rx" ]]; then
	if [[ -d "$INSDIR" ]] && [[ $1 == "ra" ]]; then
		echo -e "Uninstalling $TLNAME with all data..."
		rm -rf "$INSDIR"
		echo -e "$TLNAME uninstalled..."
	elif [[ -d "$INSDIR" ]] && [[ $1 == "rx" ]]; then
		echo -e "Uninstalling $TLNAME without data..."
		[ -e "$INSDIR"/databot ] && mv "$INSDIR"/databot "$INSDIR"-databot.bak
		rm -rf "$INSDIR"
		echo -e "$TLNAME uninstalled..."
	fi

# Edit databot command
elif [[ $1 == "e" ]]; then
	# Edit databot CMD
	echo -e "Editing $TLNAME databot..."
	echo -n "💬 Enter Bot Token: "
	read -r btoken
	echo -n "🤖 Enter Bot Username (without @): "
	read -r buser

	echo -e "\n🔨 Setting up $TLNAME with new data..."
	echo -e "$btoken" > "$INSDIR"/databot
	echo -e "$buser" >> "$INSDIR"/databot

	echo -e "✔️ $TLNAME telegram data was edited successfully."

# Runner/starter command
elif [[ $1 == "r" ]]; then
	# Run screen
	if [[ $(opkg list-installed | grep -c "^screen -") > 0 ]];then
		echo -e "Starting screen..."
		screen -S bot &>/dev/null &
	else
		echo -e "Pkg: screen is not available, exiting..."
		exit 1
	fi
	
	# Run php
	if [[ $(ls {/bin,/usr/bin,/usr/sbin} | grep -c "php8-cli") > 0 ]];then
		echo -e "Starting $TLNAME with php8-cli."
		cd "$INSDIR" && nohup php8-cli index.php &>/dev/null &
	else
		echo -e "Starting $TLNAME with php7-cli."
		cd "$INSDIR" && nohup php7-cli index.php &>/dev/null &
	fi
	
	echo -e "✔️ $TLNAME started successfully."
	echo -e "Run [jobs] command to see $TLNAME process."

# Check status command
elif [[ $1 == "c" ]]; then
	# https://linuxconfig.org/how-to-kill-a-running-process-on-linux
	if [[ $(ps -a | grep "php7-cli\|php8-cli") > 0 ]]; then
		echo -e "✔️ $TLNAME is running with detail:"
		jobs -p
		# ps -a | grep "php7-cli\|php8-cli"
	else
		echo -e "✔️ $TLNAME is not running."
		exit 0
	fi

# Stopper command
elif [[ $1 == "s" ]]; then
	# Stop CMD
	
	# https://unix.stackexchange.com/questions/383497/how-to-kill-all-jobs-in-bash/383542#383542
	# pids=( $(jobs -p) )
	# [ -n "$pids" ] && kill -- "${pids[@]/#/-}"
	
	# https://linuxconfig.org/how-to-kill-a-running-process-on-linux
	if [[ $(ps -a | grep "php7-cli\|php8-cli") > 0 ]]; then
		kill $(ps -a | grep "php7-cli\|php8-cli")
		echo -e "✔️ $TLNAME stopped successfully."
		exit 0
	else
		echo -e "✔️ $TLNAME is not running."
		exit 0
	fi

# Auto start on boot command (rc.local)
elif [[ $1 == "a" ]]; then
	if [[ -f "$INSDIR"/index.php ]] && ! grep -q "PHPTeleBotWrt" /etc/rc.local; then
		sed -i 's#exit 0##g' /etc/rc.local
		cat << 'EOF' >> /etc/rc.local
#PHPTeleBotWrt-Start
PTBWDIR="/root/PHPTeleBotWrt"
if [[ $(ls {/bin,/usr/bin,/usr/sbin} | grep -c "php8-cli") > 0 ]];then cd "$PTBWDIR" && nohup php8-cli index.php &>/dev/null &; else cd "$PTBWDIR" && nohup php7-cli index.php &>/dev/null &; fi
#PHPTeleBotWrt-End

exit 0
EOF
		echo -e "$TLNAME added to startup (rc.local).."
	else
		sed -i -e '/PHPTeleBotWrt-Start/,+4d' /etc/rc.local
		echo -e "$TLNAME removed from startup (rc.local).."
	fi

# Add bot to Scheduled Tasks (cron) command
elif [[ $1 == "t" ]]; then
	if [[ -f "$INSDIR"/index.php ]] && ! grep -q "PHPTeleBotWrt" /etc/crontabs/root; then
		sed -i 's#exit 0##g' /etc/crontabs/root
		cat << 'EOF' >> /etc/crontabs/root
#PHPTeleBotWrt-Start
*/5 * * * * cd /root/PHPTeleBotWrt && php8-cli index.php
EOF
		echo -e "$TLNAME added to Scheduled Tasks (cron).."
	else
		sed -i -e '/PHPTeleBotWrt-Start/,+1d' /etc/crontabs/root
		echo -e "$TLNAME removed from Scheduled Tasks (cron).."
	fi

# Auto start on boot command
else
	echo -e "$TLNAME Requirements:"
	echo -e " 1. Make your own bot from @BotFather."
	echo -e " 2. Copy your telegram bot token from @BotFather."
	echo -e " 2. Copy your telegram bot username from Bot profile."
	echo -e ""
	echo -e "🔄 $TLNAME Manager Usage:"
	echo -e " $SCRIPTNAME i  : Install $TLNAME."
	echo -e " $SCRIPTNAME u  : Update $TLNAME."
	echo -e " $SCRIPTNAME ra : Remove/Uninstall $TLNAME with all data."
	echo -e " $SCRIPTNAME rx : Remove/Uninstall $TLNAME without data."
	echo -e " $SCRIPTNAME e  : Edit $TLNAME databot config."
	echo -e " $SCRIPTNAME r  : Run $TLNAME."
	echo -e " $SCRIPTNAME c  : Check $TLNAME running status."
	echo -e " $SCRIPTNAME s  : Stop $TLNAME."
	echo -e " $SCRIPTNAME a  : Add/remove $TLNAME to/from Auto Startup (rc.local)."
	echo -e " $SCRIPTNAME t  : Add/remove $TLNAME to/from Scheduled Tasks (cron)."
fi
